security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Person
                property: pseudonyme  # Connexion via le pseudonyme

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home # Redirige après connexion
                always_use_default_target_path: false
            logout:
                path: app_logout
                target: home

    access_control:
         - { path: ^/project/new, roles: ROLE_USER }
         - { path: ^/dashboard, roles: ROLE_ADMIN }
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/profile, roles: ROLE_USER }
